version: '3.8'
services:
  file-gallery:
    build: .
    container_name: file_gallery_app
    volumes:
      - ./data:/var/www/html/data
    ports:
      - "8080:80"
    env_file:
      - .env # Utilisation d'un fichier .env pour les variables d'environnement
    restart: unless-stopped
