version: '3.8'
services:
  file-gallery:
    build: .
    container_name: file_gallery_app
    volumes:
      - ./data:/var/www/html/
      - ./data:/var/www/html/file_gallery/data
    ports:
      - "8080:80"
    environment:
      TIMEZONE: "Europe/Paris"
    restart: unless-stopped
